@echo off
mkdir src\app\config
mkdir src\app\constants
mkdir src\app\i18n\locales
mkdir src\app\theme
mkdir src\components\common
mkdir src\components\ui
mkdir src\features\home\components
mkdir src\features\home\screens
mkdir src\features\home\hooks
mkdir src\features\home\types
mkdir src\features\products\components
mkdir src\features\products\screens
mkdir src\features\products\hooks
mkdir src\features\products\types
mkdir src\features\categories\components
mkdir src\features\categories\screens
mkdir src\features\categories\hooks
mkdir src\features\categories\types
mkdir src\features\quotes\components
mkdir src\features\quotes\screens
mkdir src\features\quotes\hooks
mkdir src\features\quotes\types
mkdir src\features\contact\components
mkdir src\features\contact\screens
mkdir src\features\contact\hooks
mkdir src\features\contact\types
mkdir src\features\about\components
mkdir src\features\about\screens
mkdir src\features\about\hooks
mkdir src\features\about\types
mkdir src\navigation
mkdir src\services\api
mkdir src\services\storage
mkdir src\services\external
mkdir src\store\slices
mkdir src\utils
mkdir src\types
mkdir assets
echo Directories created